spring.application.name=swaggerImplementation
spring.datasource.url=jdbc:postgresql://localhost:5432/swagger

spring.datasource.username=postgres
spring.datasource.password=Nitya@2004


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true